- include_tasks: "extract.yml"
  when: fram_install_operation == 'extract' or
        fram_install_operation == 'installfram'

- include_role: 
    name: darkedges.forgerock_amster
  vars:
    amster_install_operation: installfram
  when: fram_install_operation == 'installfram'
